In [5]:
import pandas as pd

In [6]:
df=pd.read_csv('train.csv')

C:\Users\kavearaasane\AppData\Local\Temp\ipykernel_6980\3155070436.py:1: DtypeWarning: Columns (746,835) have mixed types. Specify dtype option on import or set low_memory=False.
  df=pd.read_csv('train.csv')

In [7]:
df.head()

,unique id,pred,salary,savings,exp,paid,accbl,Col8,Col9,Col10,...,Col2388,Col2389,Col2390,Col2391,Col2392,Col2393,Col2394,Col2395,Col2396,Col2397
0,RIGHGSN,1,1.086711e+04,8.648345e+03,1.576618e+04,2.890466e+04,5.273655e+03,2.346153e+04,1.285597e+04,2.871509e+04,...,0,1,0,1,214.0,214.0,68.0,22.0,22.0,7.0
1,RIMHI5ZGP,1,2.584312e+05,2.179633e+05,1.866287e+05,1.866287e+05,2.154519e+05,1.923615e+05,1.726538e+05,1.666974e+05,...,0,0,0,0,41.0,41.0,38.0,12.0,12.0,11.0
2,RIHOG1SZU,1,1.459355e+07,1.260060e+07,1.100315e+07,1.010315e+07,1.879882e+07,1.514035e+07,5.320778e+06,6.906324e+06,...,0,1,1,0,378.0,378.0,310.0,21.0,21.0,16.0
3,RIHOLMQWU,1,6.727043e+05,8.181116e+05,6.794893e+05,6.794893e+05,8.257254e+05,7.605803e+05,3.577134e+05,4.236612e+05,...,0,0,0,0,702.0,702.0,644.0,951.0,951.0,743.0
4,RIHO584ET,1,-1.218742e+06,-3.005361e+06,-1.666241e+05,-2.403574e+06,2.583183e+06,2.086546e+06,5.938358e+06,5.446532e+06,...,0,0,0,0,1305.0,1305.0,1211.0,2205.0,2205.0,1831.0

In [8]:
df.salary=df.salary/100
df.savings=df.savings/100
df.exp=df.exp/100
df.paid=df.paid/100
df.accbl=df.accbl/100

In [9]:
df.head()

,unique id,pred,salary,savings,exp,paid,accbl,Col8,Col9,Col10,...,Col2388,Col2389,Col2390,Col2391,Col2392,Col2393,Col2394,Col2395,Col2396,Col2397
0,RIGHGSN,1,108.671100,86.483450,157.661791,289.046617,52.736550,2.346153e+04,1.285597e+04,2.871509e+04,...,0,1,0,1,214.0,214.0,68.0,22.0,22.0,7.0
1,RIMHI5ZGP,1,2584.312433,2179.632725,1866.286820,1866.286820,2154.518950,1.923615e+05,1.726538e+05,1.666974e+05,...,0,0,0,0,41.0,41.0,38.0,12.0,12.0,11.0
2,RIHOG1SZU,1,145935.482300,126006.038900,110031.452400,101031.452400,187988.184600,1.514035e+07,5.320778e+06,6.906324e+06,...,0,1,1,0,378.0,378.0,310.0,21.0,21.0,16.0
3,RIHOLMQWU,1,6727.043133,8181.115750,6794.892600,6794.892600,8257.254375,7.605803e+05,3.577134e+05,4.236612e+05,...,0,0,0,0,702.0,702.0,644.0,951.0,951.0,743.0
4,RIHO584ET,1,-12187.424570,-30053.609750,-1666.240580,-24035.744940,25831.826680,2.086546e+06,5.938358e+06,5.446532e+06,...,0,0,0,0,1305.0,1305.0,1211.0,2205.0,2205.0,1831.0

In [10]:
df.tail()

,unique id,pred,salary,savings,exp,paid,accbl,Col8,Col9,Col10,...,Col2388,Col2389,Col2390,Col2391,Col2392,Col2393,Col2394,Col2395,Col2396,Col2397
17516,M9ERLMQ,1,94.046833,37.262883,37.262883,74.459633,201.700783,40340.15667,5107.963287,4950.750973,...,0,0,0,0,38.0,35.0,25.0,14.0,11.0,6.0
17517,M1W6L8S,1,656.383000,191.096818,176.184025,352.368050,46.398973,14228.05167,47750.289080,60068.752550,...,1,0,1,0,155.0,145.0,90.0,31.0,21.0,12.0
17518,MD5BL5K,1,422.094133,317.377125,253.901700,253.901700,100.505000,8040.40000,43545.777930,40971.844200,...,0,0,0,0,2.0,2.0,2.0,4.0,4.0,2.0
17519,MYLOQ8Y,1,704.849633,981.461029,981.461029,1080.079433,1317.388500,135919.15830,57247.624500,56057.621470,...,0,1,0,1,35.0,34.0,11.0,10.0,9.0,4.0
17520,M2YK6ON,1,101.919833,101.442625,101.442625,101.442625,103.696250,10369.62500,87.305993,87.305993,...,0,0,0,0,2.0,2.0,2.0,4.0,4.0,3.0

In [11]:
import gradio as gr
import numpy as np

In [12]:
from sklearn.linear_model import LogisticRegression

In [13]:
m=LogisticRegression()

In [14]:
x=df.salary+df.savings+df.exp+df.paid+df.accbl

In [15]:
y=df.pred

In [16]:
x=x.array.reshape(-1,1)

In [17]:
y=y.array.reshape(-1,1)

In [18]:
m.fit(x,y)

C:\Users\kavearaasane\anaconda3\lib\site-packages\sklearn\utils\validation.py:993: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)

LogisticRegression()

In [19]:
m.predict([[2478.5+2478.5+4375.48+4375.48+86.123333]])

array([1], dtype=int64)

In [20]:
m.score(x,y)

0.9584498601677987

In [21]:
x=m.predict([[20000+10000+15000+50000+5000]])
x

array([1], dtype=int64)

In [22]:
pip install gradio

Requirement already satisfied: gradio in c:\users\kavearaasane\anaconda3\lib\site-packages (3.9)
Requirement already satisfied: requests in c:\users\kavearaasane\anaconda3\lib\site-packages (from gradio) (2.27.1)
Requirement already satisfied: aiohttp in c:\users\kavearaasane\anaconda3\lib\site-packages (from gradio) (3.8.1)
Requirement already satisfied: pydub in c:\users\kavearaasane\anaconda3\lib\site-packages (from gradio) (0.25.1)
Requirement already satisfied: h11<0.13,>=0.11 in c:\users\kavearaasane\anaconda3\lib\site-packages (from gradio) (0.12.0)
Requirement already satisfied: pycryptodome in c:\users\kavearaasane\anaconda3\lib\site-packages (from gradio) (3.15.0)
Requirement already satisfied: paramiko in c:\users\kavearaasane\anaconda3\lib\site-packages (from gradio) (2.8.1)
Requirement already satisfied: pydantic in c:\users\kavearaasane\anaconda3\lib\site-packages (from gradio) (1.10.2)
Requirement already satisfied: python-multipart in c:\users\kavearaasane\anaconda3\lib\site-packages (from gradio) (0.0.5)
Requirement already satisfied: fastapi in c:\users\kavearaasane\anaconda3\lib\site-packages (from gradio) (0.86.0)
Requirement already satisfied: markdown-it-py[linkify,plugins] in c:\users\kavearaasane\anaconda3\lib\site-packages (from gradio) (2.1.0)
Requirement already satisfied: jinja2 in c:\users\kavearaasane\anaconda3\lib\site-packages (from gradio) (2.11.3)
Requirement already satisfied: websockets in c:\users\kavearaasane\anaconda3\lib\site-packages (from gradio) (10.4)
Requirement already satisfied: fsspec in c:\users\kavearaasane\anaconda3\lib\site-packages (from gradio) (2022.2.0)
Requirement already satisfied: numpy in c:\users\kavearaasane\anaconda3\lib\site-packages (from gradio) (1.21.5)
Requirement already satisfied: orjson in c:\users\kavearaasane\anaconda3\lib\site-packages (from gradio) (3.8.1)
Note: you may need to restart the kernel to use updated packages.
Requirement already satisfied: httpx in c:\users\kavearaasane\anaconda3\lib\site-packages (from gradio) (0.23.0)
Requirement already satisfied: pandas in c:\users\kavearaasane\anaconda3\lib\site-packages (from gradio) (1.4.2)
Requirement already satisfied: pillow in c:\users\kavearaasane\anaconda3\lib\site-packages (from gradio) (9.0.1)
Requirement already satisfied: matplotlib in c:\users\kavearaasane\anaconda3\lib\site-packages (from gradio) (3.5.1)
Requirement already satisfied: uvicorn in c:\users\kavearaasane\anaconda3\lib\site-packages (from gradio) (0.19.0)
Requirement already satisfied: pyyaml in c:\users\kavearaasane\anaconda3\lib\site-packages (from gradio) (6.0)
Requirement already satisfied: ffmpy in c:\users\kavearaasane\anaconda3\lib\site-packages (from gradio) (0.3.0)
Requirement already satisfied: frozenlist>=1.1.1 in c:\users\kavearaasane\anaconda3\lib\site-packages (from aiohttp->gradio) (1.2.0)
Requirement already satisfied: async-timeout<5.0,>=4.0.0a3 in c:\users\kavearaasane\anaconda3\lib\site-packages (from aiohttp->gradio) (4.0.1)
Requirement already satisfied: aiosignal>=1.1.2 in c:\users\kavearaasane\anaconda3\lib\site-packages (from aiohttp->gradio) (1.2.0)
Requirement already satisfied: attrs>=17.3.0 in c:\users\kavearaasane\anaconda3\lib\site-packages (from aiohttp->gradio) (21.4.0)
Requirement already satisfied: charset-normalizer<3.0,>=2.0 in c:\users\kavearaasane\anaconda3\lib\site-packages (from aiohttp->gradio) (2.0.4)
Requirement already satisfied: yarl<2.0,>=1.0 in c:\users\kavearaasane\anaconda3\lib\site-packages (from aiohttp->gradio) (1.6.3)
Requirement already satisfied: multidict<7.0,>=4.5 in c:\users\kavearaasane\anaconda3\lib\site-packages (from aiohttp->gradio) (5.1.0)
Requirement already satisfied: typing-extensions>=3.6.5 in c:\users\kavearaasane\anaconda3\lib\site-packages (from async-timeout<5.0,>=4.0.0a3->aiohttp->gradio) (4.1.1)
Requirement already satisfied: idna>=2.0 in c:\users\kavearaasane\anaconda3\lib\site-packages (from yarl<2.0,>=1.0->aiohttp->gradio) (3.3)
Requirement already satisfied: starlette==0.20.4 in c:\users\kavearaasane\anaconda3\lib\site-packages (from fastapi->gradio) (0.20.4)
Requirement already satisfied: anyio<5,>=3.4.0 in c:\users\kavearaasane\anaconda3\lib\site-packages (from starlette==0.20.4->fastapi->gradio) (3.5.0)
Requirement already satisfied: sniffio>=1.1 in c:\users\kavearaasane\anaconda3\lib\site-packages (from anyio<5,>=3.4.0->starlette==0.20.4->fastapi->gradio) (1.2.0)
Requirement already satisfied: certifi in c:\users\kavearaasane\anaconda3\lib\site-packages (from httpx->gradio) (2021.10.8)
Requirement already satisfied: httpcore<0.16.0,>=0.15.0 in c:\users\kavearaasane\anaconda3\lib\site-packages (from httpx->gradio) (0.15.0)
Requirement already satisfied: rfc3986[idna2008]<2,>=1.3 in c:\users\kavearaasane\anaconda3\lib\site-packages (from httpx->gradio) (1.5.0)
Requirement already satisfied: MarkupSafe>=0.23 in c:\users\kavearaasane\anaconda3\lib\site-packages (from jinja2->gradio) (2.0.1)
Requirement already satisfied: mdurl~=0.1 in c:\users\kavearaasane\anaconda3\lib\site-packages (from markdown-it-py[linkify,plugins]->gradio) (0.1.2)
Requirement already satisfied: linkify-it-py~=1.0 in c:\users\kavearaasane\anaconda3\lib\site-packages (from markdown-it-py[linkify,plugins]->gradio) (1.0.3)
Requirement already satisfied: mdit-py-plugins in c:\users\kavearaasane\anaconda3\lib\site-packages (from markdown-it-py[linkify,plugins]->gradio) (0.3.1)
Requirement already satisfied: uc-micro-py in c:\users\kavearaasane\anaconda3\lib\site-packages (from linkify-it-py~=1.0->markdown-it-py[linkify,plugins]->gradio) (1.0.1)
Requirement already satisfied: packaging>=20.0 in c:\users\kavearaasane\anaconda3\lib\site-packages (from matplotlib->gradio) (21.3)
Requirement already satisfied: cycler>=0.10 in c:\users\kavearaasane\anaconda3\lib\site-packages (from matplotlib->gradio) (0.11.0)
Requirement already satisfied: kiwisolver>=1.0.1 in c:\users\kavearaasane\anaconda3\lib\site-packages (from matplotlib->gradio) (1.3.2)
Requirement already satisfied: fonttools>=4.22.0 in c:\users\kavearaasane\anaconda3\lib\site-packages (from matplotlib->gradio) (4.25.0)
Requirement already satisfied: python-dateutil>=2.7 in c:\users\kavearaasane\anaconda3\lib\site-packages (from matplotlib->gradio) (2.8.2)
Requirement already satisfied: pyparsing>=2.2.1 in c:\users\kavearaasane\anaconda3\lib\site-packages (from matplotlib->gradio) (3.0.4)
Requirement already satisfied: six>=1.5 in c:\users\kavearaasane\anaconda3\lib\site-packages (from python-dateutil>=2.7->matplotlib->gradio) (1.16.0)
Requirement already satisfied: pytz>=2020.1 in c:\users\kavearaasane\anaconda3\lib\site-packages (from pandas->gradio) (2021.3)
Requirement already satisfied: bcrypt>=3.1.3 in c:\users\kavearaasane\anaconda3\lib\site-packages (from paramiko->gradio) (3.2.0)
Requirement already satisfied: pynacl>=1.0.1 in c:\users\kavearaasane\anaconda3\lib\site-packages (from paramiko->gradio) (1.4.0)
Requirement already satisfied: cryptography>=2.5 in c:\users\kavearaasane\anaconda3\lib\site-packages (from paramiko->gradio) (3.4.8)
Requirement already satisfied: cffi>=1.1 in c:\users\kavearaasane\anaconda3\lib\site-packages (from bcrypt>=3.1.3->paramiko->gradio) (1.15.0)
Requirement already satisfied: pycparser in c:\users\kavearaasane\anaconda3\lib\site-packages (from cffi>=1.1->bcrypt>=3.1.3->paramiko->gradio) (2.21)
Requirement already satisfied: urllib3<1.27,>=1.21.1 in c:\users\kavearaasane\anaconda3\lib\site-packages (from requests->gradio) (1.26.9)
Requirement already satisfied: click>=7.0 in c:\users\kavearaasane\anaconda3\lib\site-packages (from uvicorn->gradio) (8.0.4)
Requirement already satisfied: colorama in c:\users\kavearaasane\anaconda3\lib\site-packages (from click>=7.0->uvicorn->gradio) (0.4.4)

In [23]:
import gradio as gr
import pickle
with open ("model_pickle","wb") as f:
    pickle.dump(m,f)
with open ("model_pickle","rb") as f:
    z=pickle.load(f)

In [24]:
def pred(salary,saving,expenditure,paid,accountbalance,Credit_score):
    x=np.array([salary+saving+expenditure+paid+accountbalance])
    pred=z.predict([x])
    while (pred==1 and Credit_score >=6 and x>=200000 ) :
        return "probalblity is high"
    else:
        return "probalblity is less"
output=gr.outputs.Textbox()
app=gr.Interface(fn=pred,inputs=['number','number','number','number','number','number'],outputs=output)
app.launch()

C:\Users\kavearaasane\anaconda3\lib\site-packages\gradio\outputs.py:21: UserWarning: Usage of gradio.outputs is deprecated, and will not be supported in the future, please import your components from gradio.components
  warnings.warn(
C:\Users\kavearaasane\anaconda3\lib\site-packages\gradio\deprecation.py:40: UserWarning: The 'type' parameter has been deprecated. Use the Number component instead.
  warnings.warn(value)

IMPORTANT: You are using gradio version 3.9, however version 3.14.0 is available, please upgrade.
--------
Running on local URL:  http://127.0.0.1:7860

To create a public link, set `share=True` in `launch()`.

(<gradio.routes.App at 0x222aecfd3d0>, 'http://127.0.0.1:7860/', None)